default_platform(:ios)

APPS = {
  "Cliqz" => {
    target: "Cliqz",
    scheme: "Cliqz",
    configuration: "Release",

    app_group_identifier: "group.com.cliqz",

    app_identifier: "com.cliqz",
    provisioning_profile: "7fb76ca0-3239-4601-bf21-bf9fe617c35c",
    provisioning_profile_name: "match AppStore com.cliqz",

    share_to_identifier: "com.cliqz.ShareTo",
    share_to_provisioning_profile: "4b0509eb-660d-4a21-b8a4-a54a25db6b41",
    share_to_provisioning_profile_name: "match AppStore com.cliqz.ShareTo",

    open_in_identifier: "com.cliqz.OpenIn",
    open_in_provisioning_profile: "18550bb3-d4bf-48fa-9372-7acb6f21627e",
    open_in_provisioning_profile_name: "match AppStore com.cliqz.OpenIn",

    today_identifier: "com.cliqz.Today",
    today_provisioning_profile: "c6df81d6-e9bf-47bb-a019-619bb93a4f94",
    today_provisioning_profile_name: "match AppStore com.cliqz.Today",

    siri_identifier: "com.cliqz.Siri",
    siri_provisioning_profile: "6d28d3fb-d0e7-4f4e-945f-e00cce3415e0",
    siri_provisioning_profile_name: "match AppStore com.cliqz.Siri",

    sentry_slug: "cliqz-ios",
    match_branch: "cliqz",
  },
  "CliqzNightly" => {
    target: "Cliqz",
    scheme: "Cliqz",
    configuration: "Adhoc",

    app_group_identifier: "group.com.cliqz.browser.nightly",

    app_identifier: "com.cliqz.browser.nightly",
    provisioning_profile: "0067dc5b-5e61-4e5e-a808-15a2a20b43f4",
    provisioning_profile_name: "match AppStore com.cliqz.browser.nightly",

    share_to_identifier: "com.cliqz.browser.nightly.ShareTo",
    share_to_provisioning_profile: "b05942bd-0a85-4e7a-b664-fc67bab03e55",
    share_to_provisioning_profile_name: "match AppStore com.cliqz.browser.nightly.ShareTo",

    open_in_identifier: "com.cliqz.browser.nightly.OpenIn",
    open_in_provisioning_profile: "013772a0-e691-4bc5-87ad-9bbb2a86d7be",
    open_in_provisioning_profile_name: "match AppStore com.cliqz.browser.nightly.OpenIn",

    today_identifier: "com.cliqz.browser.nightly.Today",
    today_provisioning_profile: "14aa1e09-cb31-48a7-954e-0c5561d9232d",
    today_provisioning_profile_name: "match AppStore com.cliqz.browser.nightly.Today",

    siri_identifier: "com.cliqz.browser.nightly.Siri",
    siri_provisioning_profile: "73ef5ef9-c286-4f5c-a81d-aec6f24fc77d",
    siri_provisioning_profile_name: "match AppStore com.cliqz.browser.nightly.Siri",

    sentry_slug: "cliqznighly-ios",
    match_branch: "cliqz",
  }
}

def get_app(options)
  app = APPS[options[:app]]
  raise 'No such app' if app.nil?
  OpenStruct.new(app)
end

def get_version(app)
  configuration_file = "../Branding/#{app.target}/Configuration/#{app.target}#{app.configuration}.xcconfig"
  configuration = Xcodeproj::Config.new(configuration_file)
  configuration.attributes['APP_MARKETING_VERSION']
end

platform :ios do

  lane :lint do
    swiftlint(
      executable: "Pods/SwiftLint/swiftlint",
      ignore_exit_status: false
    )
  end

  lane :Build do |options|
    app = get_app(options)

    create_keychain(
      path: "/Users/vagrant/Library/Keychains/"+ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: app.match_branch,
      app_identifier: [
        app.app_identifier,
        app.share_to_identifier,
        app.open_in_identifier,
        app.today_identifier,
        app.siri_identifier,
      ],
      readonly: true,
      verbose: true
    )

    version = get_version(app)

    previous_version = 0

    begin
      previous_version = latest_testflight_build_number(
        version: version,
        app_identifier: app.app_identifier,
      )
    rescue StandardError => e
      puts "Something went wrong: #{e.inspect}"
      # latest_testflight_build_number fails if there is not build in TestFligh yet
    end

    # This step update app_identifier based on AppFile
    # Not sure how it updates ShareTo extension identifier
    increment_build_number(
      build_number: previous_version + 1,
      xcodeproj: "UserAgent.xcodeproj"
    )

    update_info_plist(
      xcodeproj: "UserAgent.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "./Branding/#{app.target}/Info.plist",
      block: proc do |plist|
        plist["SentryDSN"] = ENV["SENTRY_DSN"]
      end
    )

    disable_automatic_code_signing(
      path: "UserAgent.xcodeproj",
      code_sign_identity: "iPhone Distribution: Cliqz GmbH (2UYYSSHVUH)",
    )

    update_project_provisioning(
      xcodeproj: "UserAgent.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/#{app.provisioning_profile}.mobileprovision",
      target_filter: app.target,
      build_configuration: app.configuration,
    )

    update_project_provisioning(
      xcodeproj: "UserAgent.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/#{app.share_to_provisioning_profile}.mobileprovision",
      target_filter: "ShareTo",
      build_configuration: app.configuration,
    )

    update_project_provisioning(
      xcodeproj: "UserAgent.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/#{app.open_in_provisioning_profile}.mobileprovision",
      target_filter: "OpenIn",
      build_configuration: app.configuration,
    )

    update_project_provisioning(
      xcodeproj: "UserAgent.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/#{app.today_provisioning_profile}.mobileprovision",
      target_filter: "Today",
      build_configuration: app.configuration,
    )

    update_project_provisioning(
      xcodeproj: "UserAgent.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/#{app.siri_provisioning_profile}.mobileprovision",
      target_filter: "Siri",
      build_configuration: app.configuration,
    )

    build_app(
      workspace: "UserAgent.xcworkspace",
      clean: true,
      disable_xcpretty: true,
      scheme: app.scheme,
      configuration: app.configuration,
      skip_profile_detection: true,
      codesigning_identity: "Apple Distribution: Cliqz GmbH (2UYYSSHVUH)",
      export_method: "app-store",
      export_team_id: "2UYYSSHVUH",
      export_options: {
        # method: "app-store",
        provisioningProfiles: {
          app.app_identifier => app.provisioning_profile_name,
          app.share_to_identifier => app.share_to_provisioning_profile_name,
          app.open_in_identifier => app.open_in_provisioning_profile_name,
          app.today_identifier => app.today_provisioning_profile_name,
          app.siri_identifier => app.siri_provisioning_profile_name,
        }
      }
    )
  end

  lane :Upload do |options|
    app = get_app(options)
    version = get_version(app)

    changelog = read_changelog

    upload_to_testflight(
      changelog: changelog,
      demo_account_required: "false",
      skip_waiting_for_build_processing: "false",
      app_identifier: app.app_identifier,
    )

    download_dsyms(version: version, app_identifier: app.app_identifier)

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: app.sentry_slug,
    )
  end
end
