default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :lint do
    swiftlint(
      executable: "Pods/SwiftLint/swiftlint",
      ignore_exit_status: false
    )
  end

  lane :clearCache do
    # Remove the Cache
    # sh("cd .. && npm cache clean --force && rm -rf Cartfile.resolved Carthage node_modules Pods && rm -rf ~/Library/Caches/org.carthage.CarthageKit")
  end

  lane :prepare do
    # Run Bootstrap for Carthage
    sh("cd .. && carthage bootstrap --verbose --platform ios --color auto --cache-builds")

    # Install NPM and POD Dependencies and Run the Build Script for NPM Dependencies.
    begin
      sh("cd .. && npm install")
    rescue
      sh("cd .. && npm install")
    end
    sh("cd .. && pod install")
    sh("cd .. && npm run build")
  end

  lane :CliqzNightly do
    # Configure CommitHash
    # sh("cd .. && plutil -replace CommitHash -string $CommitHash Client/Info.plist")

    # Building ReactNative Extension
    # sh("cd .. && npm run bundle-cliqz")

    create_keychain(
      path: "/Users/vagrant/Library/Keychains/"+ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "cliqz-browser-nightly",
      app_identifier: ["com.cliqz.browser.nightly", "com.cliqz.browser.nightly.ShareTo"],
      readonly: true,
      verbose: true
    )

    version = get_version_number(
      xcodeproj: "Client.xcodeproj",
      target: "Cliqz"
    )

    previous_version = 0

    begin
      previous_version = latest_testflight_build_number(version: version)
    rescue
      # latest_testflight_build_number fails if there is not build in TestFligh yet
    end

    # This step update app_identifier based on AppFile
    # Not sure how it updates ShareTo extension identifier
    increment_build_number(
      build_number: previous_version + 1,
      xcodeproj: "Client.xcodeproj"
    )

    update_app_identifier(
      xcodeproj: "Client.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "./Client/Cliqz-Info.plist",
      app_identifier: "com.cliqz.browser.nightly" # The App Identifier
    )

    update_app_identifier(
      xcodeproj: "Client.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "./Extensions/ShareTo/Info.plist",
      app_identifier: "com.cliqz.browser.nightly.ShareTo" # The App Identifier
    )

    update_app_group_identifiers(
      entitlements_file: "Client/Entitlements/FennecApplication.entitlements",
      app_group_identifiers: ["group.com.cliqz.browser.nightly"]
    )

    update_app_group_identifiers(
      entitlements_file: "Extensions/Entitlements/Fennec.entitlements",
      app_group_identifiers: ["group.com.cliqz.browser.nightly"]
    )


    disable_automatic_code_signing(
      path: "Client.xcodeproj",
      code_sign_identity: "iPhone Distribution: Cliqz GmbH (2UYYSSHVUH)",
    )

    update_project_provisioning(
      xcodeproj: "Client.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/0d0c370e-d393-40af-a704-42def1331441.mobileprovision",
      target_filter: "Cliqz",
      build_configuration: "Adhoc",
    )

    update_project_provisioning(
      xcodeproj: "Client.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/93a334ed-4bb7-4121-b7d1-326fe0546dec.mobileprovision",
      target_filter: "ShareTo",
      build_configuration: "Adhoc",
    )

    build_app(
      workspace: "UserAgent.xcworkspace",
      clean: true,
      scheme: "Cliqz Nightly",
      skip_profile_detection: true,
      codesigning_identity: "iPhone Distribution: Cliqz GmbH (2UYYSSHVUH)",
      export_method: "app-store",
      export_team_id: "2UYYSSHVUH",
      export_options: {
        # method: "app-store",
        provisioningProfiles: {
          "com.cliqz.browser.nightly" => "match AppStore com.cliqz.browser.nightly",
          "com.cliqz.browser.nightly.ShareTo" => "match AppStore com.cliqz.browser.nightly.ShareTo",
        }
      }
    )

    upload_to_testflight(
      changelog: "Cliqz Browser Nightly update",
      demo_account_required: "false",
      skip_waiting_for_build_processing: "true",
      app_identifier: "com.cliqz.browser.nightly",
    )

    # sentry_upload_dsym(
    #   auth_token: ENV["SENTRY_AUTH_TOKEN"],
    #   org_slug: 'cliqz',
    #   project_slug: 'cliqz-ios',
    # )
  end
end
