default_platform(:ios)

platform :ios do
  lane :lint do
    swiftlint(
      executable: "Pods/SwiftLint/swiftlint",
      ignore_exit_status: false
    )
  end

  lane :CliqzNightly do
    create_keychain(
      path: "/Users/vagrant/Library/Keychains/"+ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      git_branch: "cliqz-browser-nightly",
      app_identifier: ["com.cliqz.browser.nightly", "com.cliqz.browser.nightly.ShareTo"],
      readonly: true,
      verbose: true
    )

    version = get_version_number(
      xcodeproj: "Client.xcodeproj",
      target: "Cliqz"
    )

    previous_version = 0

    begin
      previous_version = latest_testflight_build_number(version: version)
    rescue
      # latest_testflight_build_number fails if there is not build in TestFligh yet
    end

    # This step update app_identifier based on AppFile
    # Not sure how it updates ShareTo extension identifier
    increment_build_number(
      build_number: previous_version + 1,
      xcodeproj: "Client.xcodeproj"
    )

    update_info_plist(
      xcodeproj: "Client.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "./Client/Cliqz-Info.plist",
      app_identifier: "com.cliqz.browser.nightly", # The App Identifier
      block: proc do |plist|
        plist["SentryDSN"] = ENV["SENTRY_DSN"]
      end
    )

    update_app_identifier(
      xcodeproj: "Client.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "./Extensions/ShareTo/Info.plist",
      app_identifier: "com.cliqz.browser.nightly.ShareTo" # The App Identifier
    )

    update_app_group_identifiers(
      entitlements_file: "Client/Entitlements/UserAgent.entitlements",
      app_group_identifiers: ["group.com.cliqz.browser.nightly"]
    )

    update_app_group_identifiers(
      entitlements_file: "Extensions/Entitlements/UserAgent.entitlements",
      app_group_identifiers: ["group.com.cliqz.browser.nightly"]
    )

    disable_automatic_code_signing(
      path: "Client.xcodeproj",
      code_sign_identity: "iPhone Distribution: Cliqz GmbH (2UYYSSHVUH)",
    )

    update_project_provisioning(
      xcodeproj: "Client.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/0d0c370e-d393-40af-a704-42def1331441.mobileprovision",
      target_filter: "Cliqz",
      build_configuration: "Adhoc",
    )

    update_project_provisioning(
      xcodeproj: "Client.xcodeproj",
      profile: "/Users/vagrant/Library/MobileDevice/Provisioning Profiles/93a334ed-4bb7-4121-b7d1-326fe0546dec.mobileprovision",
      target_filter: "ShareTo",
      build_configuration: "Adhoc",
    )

    build_app(
      workspace: "UserAgent.xcworkspace",
      clean: true,
      disable_xcpretty: true,
      scheme: "Cliqz Nightly",
      skip_profile_detection: true,
      codesigning_identity: "iPhone Distribution: Cliqz GmbH (2UYYSSHVUH)",
      export_method: "app-store",
      export_team_id: "2UYYSSHVUH",
      export_options: {
        # method: "app-store",
        provisioningProfiles: {
          "com.cliqz.browser.nightly" => "match AppStore com.cliqz.browser.nightly",
          "com.cliqz.browser.nightly.ShareTo" => "match AppStore com.cliqz.browser.nightly.ShareTo",
        }
      }
    )
  end

  lane :TestFlight do
    changelog = read_changelog

    upload_to_testflight(
      changelog: changelog,
      demo_account_required: "false",
      skip_waiting_for_build_processing: "false",
      app_identifier: "com.cliqz.browser.nightly",
    )

    sentry_upload_dsym(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'cliqz',
      project_slug: 'cliqznighly-ios',
    )
  end
end
